version: '3'
services:
  app:
    build: .
    image: chaspy/learngit
    container_name: learngit
    ports:
      - 3000:3000
    volumes:
      - ./app:/src
    command: [sh, -c, npm install && npm start]
